; SonarQube project configuration file
# Configurações do SonarQube para o projeto API_SOLID_CI
sonar.projectName=findAfriend
sonar.projectVersion=1.0
sonar.projectDescription= findAfriend - SonarQube


# Credenciais do SonarQube - Configurar para executar o SonarQube Scanner com o script npm run sonar do pacote.json
sonar.host.url=http://172.26.0.4:9000
sonar.projectKey=findAfriend
sonar.login=sqp_de4a4dc465921b99d6ca3f69690fb98d61f3e8d2

# Configurações Configurações Gerais
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/build/**,**/*.d.ts

# Configurações para Vitest (cobertura)
sonar.typescript.lcov.reportPaths=coverage/lcov.info
