# services:
#   app:
#     build:
#       context: ..  # 👈 Isso aponta para o diretório pai (onde está o package.json)
#       dockerfile: docker/Dockerfile  # 👈 Caminho para o Dockerfile
#     container_name: FAF_APP
#     restart: unless-stopped
#     networks:
#       FAF_API:
#         ipv4_address: 172.27.0.3
#     ports:
#       - "3333:3333"
#     volumes:
#       - ../:/usr/src/app  # 👈 Volume também aponta para o diretório pai
#       - /usr/src/app/node_modules  # Evita sobrescrever node_modules
#     environment:
#       - DATABASE_URL="postgresql://usuario_dump:senha_dump@172.27.0.30:5432/banco_dump?schema=public"

# networks:
#   FAF_API:
#     name: FAF_API
#     external: true

# volumes:
#   app_data:



services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: FAF_APP
    restart: unless-stopped
    networks:
      FAF_API:
        ipv4_address: 172.27.0.3
    ports:
      - "3333:3333"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://usuario_dump:senha_dump@172.27.0.30:5432/banco_dump?schema=public
      - NODE_ENV=productions
    develop:
      watch:
        - action: sync
          path: ..
          target: /usr/src/app
        - action: rebuild
          path: package.json

networks:
  FAF_API:
    name: FAF_API
    external: true

volumes:
  app_data: