name: Run Unit Tests

on:
  push:
    branches: [ci_cd]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # - run: npm run test:unit
      - name: Run Unit Tests with Environment Variables 🧪
        run: npm run test:unit
        # 🔑 Adicione a variável de ambiente necessária aqui
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}